### ISSUE TITLE
New Octoherd script to download files

### ISSUE THREAD

**Issue by stefanbuck** [stefanbuck/script-download-files#1]
Hi @gr2m @oscard0m, I'm using this octoherd script quite a lot to analyse repository data. If you both agree I would like to move this repo to the @octoherd org to leverage the existing publish automation.

**Comment by gr2m** [comment]
Did you use `npm init octoherd-script` to setup this repository? It should have created an initial pull request with instructions on how to setup auto-release. I can also help you setup release-automation for this repository if you like? You should also add the [octoherd-script](https://github.com/topics/octoherd-script) topic to the repository and install [the octoherd app](https://github.com/apps/octoherd)

**Comment by stefanbuck** [comment]
No, I did not. I used https://github.com/octoherd/script-archive-repository as a base for this repo. I can setup the repo as suggested or move it into octoherd, I really don't mind either way. From a discoverability point of view having the repo within octoherd might be interesting, but I do remember a similar discussion from last time. As said, I have a small preference but I'm open either way.

**Comment by gr2m** [comment]
I'd appreciate if you could go the `npm init octoherd-script` path and let me know how it went. It should walk you through the entire process

**Comment by stefanbuck** [comment]
Apart from one tiny typo [see](https://github.com/stefanbuck/octoherd-script-download-files/pull/1/commits/2b305220f845c5733dda078d7e265e963abdf796#r975816116) the process was very smooth and clear.

**Comment by stefanbuck** [comment]
Mhhh the [initial released failed](https://github.com/stefanbuck/octoherd-script-download-files/actions/runs/3093478112/jobs/5006007239). The secret `NPM_TOKEN` exists and the overall setup looks correct. @gr2m any idea how to debug this further?

**Comment by gr2m** [comment]
Hmm very odd, that error doesn't say much. Do you know if you set `NPM_TOKEN` to an automation token?

Can you try the following

1. Delete the `v1.0.0` tag
2. Replace `npx semantic-release` with `npx semantic-release --debug`

The new commit should trigger a new release. I hope the `--debug` will give us more insights

**Comment by stefanbuck** [comment]
Yes, it's an automation token. I added this debug flag, but I can't spot any obvious in the logs. Anyway it's late and catching sleep often helps with stuff like like this

**Comment by gr2m** [comment]
Super odd.

So next two things I'd try is to

1. Log out the debug logs that npm created, add a step after running `npx semantic-release`: 

   ```yml
   - run:  cat /home/runner/.npm/_logs/*.log
     if: ${{ failure() }}
   ```
1. try to publish the package from your local machine. Replace `"version"` in package.json with `1.0.0`, then run `npm publish`. If that works, you'll have to create the v1.0.0 release manually on GitHub to keep npm/github in sync

**Comment by gr2m** [comment]
I contacted the npm registry team, no response yet. My @semantic-release co-maintainer Matt also looked into it, but is puzzled as well. He says usually there is more information coming in a response from the registry than just an error code.

**Comment by stefanbuck** [comment]
Thanks gr2m, I really appreciate your help, but I found the issue. Turns out npm doesn't like package names that include `download`. I renamed the package to `octoherd-script-get-files` https://www.npmjs.com/package/octoherd-script-get-files ...
